# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ordersdb
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate dialect for Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Secret key for JWT (in a real application, use a secure method to store this)
jwt.secret=i3L/txEvQIjo9O+YMMpBxIkvBTMrk0DiaNXPhaAi4P4ErtJUo8//v+8goMRNJIZxlSRCGIDCSoFF4s461EXlEA==
jwt.expiration=3600000
